
== Resources and References

* https://learn.openshift.com/operatorframework/


== Development Workflow

. Install docker or podman, and make
. `$ git clone https://github.com/RedHatGov/tssc-operator.git`
. `cd tssc-operator`
. `$ oc login` <- as cluster admin
. `$ hack/operate.sh -o namespaced` <- install the operator. It will be deployed into the tssc-operator-system namespace by default.
. Create a CR for whatever you're testing. You can check the config/samples directory. For example: `oc apply -f config/samples/redhatgov_v1alpha1_tsscplatform.yaml -n tssc-operator-system`. This will provision a TsscPlatform in the tssc-operator-system namespace.
. If you make some Ansible changes and need to test them, you need to rebuild the operator image. 
.. Carefully cleanup the tssc-operator-system project (so as not to orphan resources and leave the project stuck in Terminating) by deleting the CustomResources that have been created (e.g. oc delete -n tssc-operator-system ArgoCD,CheCluster,Gitea,Mattermost,Nexus,QuayEcosystem,Keycloak,SeleniumGrid,Sonarqube --all), and then removing the operator installation by running hack/operate.sh -r
.. Override the default operator image in a shell variable: IMAGE=quay.io/<your quay username>/tssc-operator
.. Build and push the image (requires a container runtime on your local): hack/operate.sh --image $IMAGE --version latest --push-only. If this is the first time you're doing this, you'll need to login to quay.io and change your repo from Private to Public so OCP can pull it
.. Deploy the operator from your new image: hack/operate.sh -o namespaced --image $IMAGE --version latest
.. Recreate the CR: oc apply -f config/samples/redhatgov_v1alpha1_tsscplatform.yaml -n tssc-operator-system

=== Testing

Currently, the best way to test development progress on the operator is to execute an install and deployment into an existing OpenShift cluster.

The process of releasing an operator into a catalog that can then be managed and deployed by OpenShift's OLM can be lengthy. For this reason, `hack/operate.sh` provides the means for: creating an operator image, pushing it to a registry and installing the operator from said public image. This allows for more effective and efficient cycles during the development phase of the operator. 

In order to test this operator in an existing OpenShift cluster, please execute the following steps:

. `$ oc login` <- as cluster admin
. `$ docker login quay.io` <- login using your quay account where the images will be pushed/pulled for testing purposes
. Create a repository in Quay.io called `tssc-operator`
. Edit your local `./config/manager/kustomization.yaml` and `./hack/operate.conf` to point to your repository created in the previous step (don't stage and commit these changes upstream)
. `$ hack/operate.sh -r` <- remove any existing deployments of the operator
. `$ hack/operate.sh --push-only` <- build and push to Quay.io a copy of your local operator code
. `$ hack/operate.sh` <- install the operator on your OpenShift cluster
. `$ oc apply -f config/samples/redhatgov.io_tsscplatforms.yaml -n tssc-operator-system` <- deploy an instance of the TSSC operator from the CustomResourceDefinition into the `tssc-operator-system`

Note: For development cycles, repeat steps 5-8.

== PR Testing

describe current TravisCI integration

== Process for Publishing a Release of the Operator


